CREATE TABLE USER (
    USERID          INTEGER             PRIMARY KEY,
    USERNAME        VARCHAR(50)         NOT NULL UNIQUE,
    USERPHONE       VARCHAR(10)         NOT NULL,
    USERLOCATION    VARCHAR(255)        NOT NULL,
    USERPROFPIC     VARCHAR(255)        NOT NULL,
    USEREMAIL       VARCHAR(255)        NOT NULL UNIQUE,
    USERPASSWORD    VARCHAR(50)         NOT NULL,
    USERCREATEDATE  TIMESTAMP           DEFAULT CURRENT_TIMESTAMP,
    USERTYPE        VARCHAR(20)         CHECK (USERTYPE IN ('Owner', 'Adopter'))
);

CREATE TABLE ADMIN (
    ADMINID         INTEGER             PRIMARY KEY,
    ADMINUSERNAME   VARCHAR(50)         NOT NULL UNIQUE,
    ADMINPASS       VARCHAR(50)         NOT NULL
);

CREATE TABLE TYPE (
    TYPEID          INTEGER             PRIMARY KEY,
    TYPENAME        VARCHAR(50)         NOT NULL UNIQUE
);

CREATE TABLE BREED (
    BREEDID         INTEGER             PRIMARY KEY,
    BREEDNAME       VARCHAR(50)         NOT NULL UNIQUE
);

CREATE TABLE TAG (
    TAGID           INTEGER             PRIMARY KEY,
    TAGNAME         VARCHAR(50)         NOT NULL UNIQUE
);

CREATE TABLE PET (
    PETID          INTEGER             PRIMARY KEY,
    PETNAME        VARCHAR(50)         NOT NULL,
    PETLOCATION    VARCHAR(255)        NOT NULL,
    PETAGE         INTEGER             NOT NULL,
    PETDESCRIPT    TEXT                NOT NULL,
    PETSTATUS      VARCHAR(50),
    BREEDID        INTEGER             NOT NULL REFERENCES breed(BREEDID) ON DELETE CASCADE ON UPDATE CASCADE,
    TYPEID         INTEGER             NOT NULL REFERENCES type(TYPEID) ON DELETE CASCADE ON UPDATE CASCADE,
    USERID         INTEGER             NOT NULL REFERENCES user(USERID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PET_TAG (
    PETID         INTEGER             NOT NULL,
    TAGID         INTEGER             NOT NULL,
    PRIMARY KEY (PETID, TAGID),
    FOREIGN KEY (PETID)               REFERENCES pet(PETID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (TAGID)               REFERENCES tag(TAGID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE POST (
    POSTID          INTEGER             PRIMARY KEY,
    POSTDATE        TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP,
    POSTIMAGE       VARCHAR(255)        NOT NULL,
    POSTDESCRIPT    TEXT,
    PETID           INTEGER             NOT NULL REFERENCES pet(PETID) ON DELETE CASCADE ON UPDATE CASCADE,
    USERID          INTEGER             NOT NULL REFERENCES user(USERID) ON DELETE CASCADE ON UPDATE CASCADE,
    TAGID           INTEGER             NOT NULL REFERENCES tag(TAGID) ON DELETE CASCADE ON UPDATE CASCADE,
    TYPEID          INTEGER             NOT NULL REFERENCES type(TYPEID) ON DELETE CASCADE ON UPDATE CASCADE,
    BREEDID         INTEGER             NOT NULL REFERENCES breed(BREEDID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ADOPTIONREQ (
    REQID           SERIAL PRIMARY KEY,
    REQSTATUS       VARCHAR(20)             CHECK (REQSTATUS IN ('Pending', 'Approved', 'Rejected', 'Completed')),
    REQDATE         TIMESTAMP               DEFAULT CURRENT_TIMESTAMP,
    PETID           INTEGER                 NOT NULL,
    USERID          INTEGER                 NOT NULL,
    FOREIGN KEY     (PETID)                 REFERENCES PET (PETID),
    FOREIGN KEY     (USERID)                REFERENCES USER (USERID)
);

CREATE TABLE REQHISTORY (
    HISTORYID       SERIAL PRIMARY KEY,
    STATUSOLD       VARCHAR(20),
    STATUSNEW       VARCHAR(20),
    CHANGEDAT       TIMESTAMP               DEFAULT CURRENT_TIMESTAMP,
    CHANGEDBY       INTEGER                 NOT NULL,
    REQID           INTEGER                 NOT NULL,
    FOREIGN KEY     (CHANGEDBY)             REFERENCES USER (USERID),
    FOREIGN KEY     (REQID)                 REFERENCES ADOPTIONREQ (REQID)
);

CREATE TABLE REVIEW (
    REVID           SERIAL PRIMARY KEY,
    REVRATING       INTEGER                 CHECK (REVRATING BETWEEN 1 AND 5),
    REVDESCRIPT     TEXT,
    REVDATE         TIMESTAMP               DEFAULT CURRENT_TIMESTAMP,
    REVRATEDBY      INTEGER                 NOT NULL,
    USERID          INTEGER                 NOT NULL,
    FOREIGN KEY     (REVRATEDBY)            REFERENCES USER (USERID),
    FOREIGN KEY     (USERID)                REFERENCES USER (USERID)
);

CREATE TABLE MESSAGE (
    MSGID           SERIAL PRIMARY KEY,
    MSGCONTENT      TEXT                    NOT NULL,
    MSGTIME         TIMESTAMP               DEFAULT CURRENT_TIMESTAMP,
    SENDERID        INTEGER                 NOT NULL,
    RECEIVERID      INTEGER                 NOT NULL,
    POSTID          INTEGER,
    FOREIGN KEY     (SENDERID)              REFERENCES USER (USERID),
    FOREIGN KEY     (RECEIVERID)            REFERENCES USER (USERID),
    FOREIGN KEY     (POSTID)                REFERENCES POST (POSTID)
);